name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --local --unset-all 'http.https://github.com/.extraheader' || true
          git remote add hf https://hackedghost:$HF_TOKEN@huggingface.co/spaces/hackedghost/op_anime
          git push hf main --force
